@startuml Диаграмма базы данных

entity User {
  * id: TEXT
  --
  login: TEXT
  FIO: TEXT
  password_hash: TEXT
  created_at: DATETIME
}

entity Manager {
  user_id: TEXT
}

entity Item {
  * id: TEXT
  --
  name: TEXT
  article: INT
  price: NUMERIC
  created_at: DATETIME
}

entity Cart_Item {
  * user_id: TEXT
  * item_id: INT
  --
  amount: INT
}

entity Order {
  * id: TEXT
  --
  user_id: TEXT
  total_price: NUMERIC
  final_price: NUMERIC
  status: "new" | "packed" | "completed" | "cancelled"
  created_at: DATETIME
}

entity Order_Item {
  * id: TEXT
  --
  item_id: INT
  order_id: INT
  amount: INT
}

Manager -- User

Order --* User

Cart_Item --* Item
Cart_Item --* User

Order_Item --* Item
Order_Item --* Order

@enduml
