@startuml states
left to right direction

state login as "<img https://www.plantuml.com/plantuml/png/SoWkIImgAKxCAL78oK_FpEEgvb9Gi4cokp3fOkk5VHUsA5pOf72nySAEYuqNcovilR3dOZDGFhGujIWlCJTLeKP1gHJALWAA1oGM5vVd5wM0nBM0G048GEBHpebvoQaviK3nQ0K5Vs-WS2nNBPT3QbuAo6O0>"
state register as "<img https://www.plantuml.com/plantuml/png/SoWkIImgAKxCAL6uiE32rWkRB-ous7YnwMB3XGqNsu3iVeKBcnGkDa94WV9xBcpbgkPIKB19iYDMFL3rXHaNze2azb_OTs7tnPuBsu7q9g0Ea8hTG0a5XHe5fTBYrAAynDnK9P26-K3P1eXg1JY0gDC20X0JeWwePil59g1fMu7gjm3j1Pe9j0YX7LrBj7DYNd9gJYoAeT4A2lxUG5OiLosNGsfU2YX0k000>"
state item_list as "<img https://www.plantuml.com/plantuml/png/PP9FIiDG4CRtESM05qXRAov4kdCb5EnEkeYqs69DfQbGiOMOBXHQKKfN1Ic2k8xHaDV4n2jyxmgUm2CupPzOy2rcthpvVZE1BnMZh_NwXjRf4vxn1I5l4C4dQN5oO4jpdPLhXVXmJCynPdA25Qi4GS0ZnXZbsiMddDHfo98bedYUJp_B-NtozWA1G4wb9SrwF6qKnxsJVInWCsyZOEoTy04tBLsialLRSShqJx3XmU4OGi3DMiEu-IXDfWLyEKQGlht2HGWxhHQ84438MxZnXpk8yl7jQgkhDwcmGzLUbmwr0J6agceXtr5GlwqmlwivUQIT6vVwAHre7MrmHKQnd935d2nkaEK_iDPgwsSNMeDgsxjgfcMmb8Eb3R2KWAD_jimHuGqs70XfoUc6ZmI7u2EI9Zm8X7ASE3BZvXq4mUFB0npu49aroaYfDFN6-lVu1G00>"
' state s2 as "<img >"
' state s3 as "<img >"
' state s4 as "<img >"
' state s5 as "<img >"

[*] --> login

login --> [*]
login --> Ошибка : Неверный логин или пароль
login --> register

register --> [*]
register --> Ошибка : Пароли не совпадают
register --> Ошибка : Пользователь с таким именем уже существует
register --> Ошибка : Не заполнены все поля

register --> login

login --> item_list
register --> item_list
