@startuml Старый бизнес процесс

|#LightBlue|Покупатель|
|#Pink|Менеджер|

|Покупатель|
start
:Выбор товара в магазине
либо заказ по телефоону;

|Менеджер|
:Проверка наличия товара в магазине;
if (Товар есть в магазине?) is (Да) then
else (Нет)
  :Записывает информацию о заказе;
  :Уведомляет покупателя по поступлении;
endif
:Оформляет продажу;
:Фиксирует данные о покупке
в журнале/таблице;
:Передача товара покупателю;
stop

@enduml