@startuml old_business_process

|#LightBlue|Покупатель|
|#Pink|Продавец-консультант|
|#LightGreen|Менеджер|
|#Orange|Администратор склада|

|Покупатель|
start
:Выбор товара в магазине;

|Продавец-консультант|
:Проверка наличия товара в магазине;
if (Товар есть в магазине?) is (Да) then
else (Нет)
  |Менеджер|
  :Отправка запроса на склад для доставки товара;

  |Администратор склада|
  :Отправка товара;

  |Продавец-консультант|
  :Оповещение покупателя о доставке товара в магазин;
endif
:Оформление продажи;
:Передача товара покупателю;
stop

@enduml