@startuml Диграмма прецедентов
left to right direction
skinparam actorStyle awesome

actor Менеджер as manager
actor Покупатель as customer
' Физ. лицо или компания

customer --> (Зарегестрироваться)
customer --> (Сделать заказ)
customer --> (Посмотреть статус заказа)
customer --> (Посмотреть историю заказов)

manager --> (Добавить товары)
' Можно импортировать список из excel
manager --> (Обработать заказ)
manager --> (Отдать готовый заказ)

@enduml
