@startuml old_business_process

|#LightBlue|Покупатель|
|#LightGreen|Продавец-консультант|
|#Pink|Менеджер|
|#Orange|Администратор склада|

|Покупатель|
start
:Приходит в магазин и выбирает товар;

|Продавец-консультант|
:Оформление продажи;
:Отправка заказа на склад для подтверждения наличия товара;

|Администратор склада|
:Проверка наличия товара на складе;
:Если товара нет в филиале, создание заявки на доставку товара в магазин;
:Подтверждение заказа и передача информации менеджеру;

|Менеджер|
:Уведомление покупателя о наличии товара в магазине;
:Формирование счета на оплату;
:Прием оплаты от покупателя;

|Покупатель|
:Ожидает получения товара;

|Продавец-консультант|
:Передача товара покупателю;
stop

@enduml
