@startsalt Корзина товаров
{
  [Вернуться к списку товаров]
  <b>Корзина товаров
  {#
    <b>Название        | <b>Цена  | <b>Количество | .   | .
    iPhone 16 Pro Max  | 203 199₽ | "  1"         | [+] | [-]
    Samsung Galaxy s25 | 194 999₽ | "  1"         | [+] | [-]
    Thinkpad T480      | 34 523₽  | "  1"         | [+] | [-]
  }
  Сумма: 432 721₽
  {
    [Оформить заказ] | [Очистить корзину]
  }
}
@endsalt
