@startsalt Заказ
{
  [Вернуться к списку заказов]
  Заказ от <b>21.03.2025
  {#
    <b>Название        | <b>Цена  | <b>Количество
    iPhone 16 Pro Max  | 203 199₽ | 1
    Samsung Galaxy s25 | 194 999₽ | 1
    Thinkpad T480      | 34 523₽  | 1
  }
  Сумма: <b>432 721₽
  Статус: <b>Собирается
  [Отменить заказ]
}
@endsalt
