@startsalt История заказов
{
  [Вернуться к списку товаров]
  <b>История заказов
  {#
    <b>Сумма | <b>Дата    | <b>Статус  | .
    432 721₽ | 21.03.2025 | Собирается | [<&fullscreen-enter>]
    1 999₽   | 12.03.2025 | Собран     | [<&fullscreen-enter>]
    5 499₽   | 23.02.2025 | Завершен   | [<&fullscreen-enter>]
  }
  Всего: <b>440 219₽
}
@endsalt
