@startsalt Список товаров
{
  {
    [Выйти из системы] | [Поиск 🔍] | [Фильтр]
  }
  <b>Список товаров
  {#
    <b>Название        | <b>Артикул | <b>Цена  | <b>Количество | .
    iPhone 16 Pro Max  | 0001       | 203 199₽ | 100           | [] .
    Samsung Galaxy s25 | 0002       | 194 999₽ | 50            | [] .
    Thinkpad T480      | 0003       | 34 523₽  | 30            | [X] .
  }
  {
    [Перейти в корзину] | [История заказов]
  }
}
@endsalt
