@startsalt Список заказов для менеджера
{
  [Вернуться к списку товаров]
  <b>Список заказов
  {#
    <b> Покупатель | <b>Сумма | <b>Дата    | <b>Статус  | .
    Иванов И.И.    | 432 721₽ | 21.03.2025 | Собирается | [<&fullscreen-enter>]
    Петров П.П.    | 1 999₽   | 12.03.2025 | Собран     | [<&fullscreen-enter>]
    Пупкив В.В.    | 5 499₽   | 23.02.2025 | Завершен   | [<&fullscreen-enter>]
  }
  Всего: <b>440 219₽
}
@endsalt
