@startsalt Регистрация в системе
{
  <b>Регистрация в системе
  Имя пользователя     | "username"
  Пароль               | "****    "
  Подтвердите пароль   | "****    "
  [Зарегистрироваться] | [Вход в систему]
}
@endsalt
